### ISSUE TITLE
Support backticks in property values

### ISSUE THREAD

**Issue by cyberbiont** [jsonicjs/jsonic#20]
Currently jsonic converts `` `string` `` to `` "`string`" ``

**Comment by rjrodger** [comment]
some example code would actually be useful here - thanks

**Comment by cyberbiont** [comment]
Take the following JS:
```js
{
    a: `b`,
}
```
copy it to JSON file

Run it through Jsonic
you'll get
```json
{
  "a": "`b`"
}
```
instead of 
```json
{
  "a": "b"
}
```
Backticks should be stripped out

**Comment by rjrodger** [comment]
backticks now support multiline values
