### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by lazytyper** [jsonicjs/jsonic#28]
I've been testing jsonic for a few minutes and discovered several issues:

1. JSON file can contain just a number or string:

```javascript
JSON.parse('0')
// -> 0
JSON.parse('"a string"')
// -> 'a string'
```

jsonic cannot parse this, but should be compatible to JSON.

2. Hexadecimal number support ?

```javascript
{ 0x12: 0x14 }
// -> { '18': 20 }
jsonic('{0x12:0x14}')
{ '0x12': '0x14' }
```

The result is not what I expected (same result as in JS). Hexadecimal numbers could be supported.
And invalid numbers like `0g12` could cause a parse error.

3. Strings without quote

I don't really like that way string don't require quotes. It can confuse and it's not much work to add two quotes.

Example:

```javascript
var name = 'John Doe';
var o = { name: name }
```
I don't need to tell what the result of js and jsonic is.
And `{ name: John Joe }` is not even valid JS.
Better: disable that by default, and require quotes.
If the programmer badly wants the short syntax, it could be turned on optionally.

**Comment by rjrodger** [comment]
these are now mostly fixed
